config/routes.rb
Rails.application.routes.draw do
  routes_config = Proc.new {
    if ENV.key?('PWPUSH_COM')
      match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
    end

    localized do
      apipie
      devise_for :users, skip: :registrations, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations'
      }

      if Settings.disable_signups
        allowed_reg_routes = %i[edit update]
      else
        allowed_reg_routes = %i[new create edit update]
      end

      devise_scope :user do
        resource  :registration,
                  only: allowed_reg_routes,
                  path: 'users',
                  path_names: { new: 'sign_up' },
                  controller: 'users/registrations',
                  as: :user_registration do
                    get :cancel
                    get :token
                    delete :token, action: :regen_token
                  end
      end

      # Dashboard controller has been removed.  Maintain this remapping for now.
      get '/d/active', to: 'passwords#active'
      get '/d/expired', to: 'passwords#expired'

      resources :p, controller: :passwords, as: :passwords, except: %i[index edit update] do
        get 'preview', on: :member
        get 'passphrase', on: :member
        post 'access', on: :member
        get 'r', on: :member, as: 'preliminary', action: 'preliminary'
        get 'audit', on: :member
        get 'active', on: :collection
        get 'expired', on: :collection
      end

      # File pushes only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_file_pushes
        resources :f, controller: :file_pushes, as: :file_pushes, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      # URL based pushes can only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_url_pushes
        resources :r, controller: :urls, as: :urls, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      resources :c, controller: :commands, as: :commands, allow: %i[create]
      # get '/slack_direct_install', to: redirect("https://slack.com/oauth/authorize?client_id=#{SLACK_CLIENT_ID}&scope=commands", status: 302)
      get '/pages/*id' => 'pages#show', as: :page, format: false
      resources :feedbacks, only: %i[new create]
      root to: 'passwords#new'
    end
  }

  # This allows for running the application in a subfolder.  See config/settings.yml (relative_root)
  if Settings.relative_root
    scope("#{Settings.relative_root}/:locale") do
      routes_config.call
    end
    # Remap the root to the default locale
    get Settings.relative_root, to: redirect("/#{Settings.relative_root}/#{I18n.default_locale}", status: 302)
  else
    routes_config.call
  end
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :views, dependent: :destroy
  has_encrypted :payload, :note, :passphrase
  
  belongs_to :user, :optional => true
  
  def to_param
    url_token.to_s
  end

  def days_old
    (Time.now.to_datetime - created_at.to_datetime).to_i
  end

  def days_remaining
    [(expire_after_days - days_old), 0].max
  end

  def views_remaining
    [(expire_after_views - view_count), 0].max
  end

  def view_count
    views.where(kind: 0).size
  end

  def successful_views
    views.where(successful: true, kind: 0).order(:created_at)
  end

  def failed_views
    views.where(successful: false, kind: 0).order(:created_at)
  end

  # Expire this password, delete the password and save the record
  def expire
    self.expired = true
    self.payload = nil
    self.passphrase = nil
    self.expired_on = Time.now
    save
  end

  # Override to_json so that we can add in <days_remaining>, <views_remaining>
  # and show the clear password
  def to_json(*args)
  # def to_json(owner: false, payload: false)
    attr_hash = attributes

    owner = false
    payload = false

    owner = args.first[:owner] if args.first.key?(:owner)
    payload = args.first[:payload] if args.first.key?(:payload)

    attr_hash['days_remaining'] = days_remaining
    attr_hash['views_remaining'] = views_remaining

    # Remove unnecessary fields
    attr_hash.delete('payload_ciphertext')
    attr_hash.delete('note_ciphertext')
    attr_hash.delete('passphrase_ciphertext')
    attr_hash.delete('user_id')
    attr_hash.delete('id')

    attr_hash.delete('passphrase')
    attr_hash.delete('note') unless owner
    attr_hash.delete('payload') unless payload

    Oj.dump attr_hash
  end

  ##
  # validate!
  #
  # Run basic validations on the password.  Expire the password
  # if it's limits have been reached (time or views)
  #
  def validate!
    return if expired

    # Range checking
    self.expire_after_days  ||= Settings.url.expire_after_days_default
    self.expire_after_views ||= Settings.url.expire_after_views_default

    unless expire_after_days.between?(Settings.url.expire_after_days_min, Settings.url.expire_after_days_max)
      self.expire_after_days = Settings.url.expire_after_days_default
    end

    unless expire_after_views.between?(Settings.url.expire_after_views_min, Settings.url.expire_after_views_max)
      self.expire_after_views = Settings.url.expire_after_views_default
    end

    return if new_record?

    expire if !days_remaining.positive? || !views_remaining.positive?
  end
end

app/controllers/urls_controller.rb
require 'securerandom'

class UrlsController < ApplicationController
  helper UrlsHelper

  # Authentication always except for the following:
  acts_as_token_authentication_handler_for User, except: [:show, :new, :preliminary, :passphrase, :access]

  resource_description do
    name 'URL Pushes'
    short 'Interact directly with URL pushes.  This feature (and corresponding API) is currently in beta.'
  end

  api :GET, '/r/:url_token.json', 'Retrieve a URL push.'
  param :url_token, String, desc: 'Secret URL token of a previously created push.', :required => true
  formats ['json']
  example 'curl -X GET -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" https://pwpush.com/r/fk27vnslkd.json'
  description "Retrieves a push including it's payload and details.  If the push is still active, this will burn a view and the transaction will be logged in the push audit log."
  def show
    redirect_to :root && return unless params.key?(:id)

    begin
      @push = Url.includes(:views).find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      # Old, expired & anonymous pushes have no value to anybody.
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'urls/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    # This url may have expired since the last view.  Validate the url
    # expiration before doing anything.
    @push.validate!

    if @push.expired
      log_view(@push)
      respond_to do |format|
        format.html { render template: 'urls/show_expired', layout: 'naked' }
        format.json { render json: @push.to_json(payload: true) }
      end
      return
    end

    # Passphrase handling
    if !@push.passphrase.nil? && !@push.passphrase.blank?
      # Construct the passphrase cookie name
      name = @push.url_token + '-' + 'r'

      # The passphrase can be passed in the params or in the cookie (default)
      # JSON requests must pass the passphrase in the params
      has_passphrase = params.fetch(:passphrase, nil) == @push.passphrase || cookies[name] == @push.passphrase_ciphertext

      if !has_passphrase
        # Passphrase hasn't been provided or is incorrect
        # Redirect to the passphrase page
        respond_to do |format|
          format.html { redirect_to passphrase_url_path(@push.url_token) }
          format.json { render json: { error: "This push has a passphrase that was incorrect or not provided." } }
        end
        return
      end

      # Delete the cookie
      cookies.delete name
    end

    log_view(@push)
    expires_now

    respond_to do |format|
      format.html { redirect_to @push.payload, allow_other_host: true, status: 303 }
      format.json { render json: @push.to_json(payload: true) }
    end

    @push.expire if !@push.views_remaining.positive?
  end

  # GET /r/:url_token/passphrase
  def passphrase
    begin
      @push = Url.find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      #
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      #
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'urls/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    respond_to do |format|
      format.html { render action: 'passphrase', layout: 'naked' }
    end
  end

  # POST /r/:url_token/access
  def access
    begin
      @push = Url.find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      #
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      #
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'urls/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    # Construct the passphrase cookie name
    name = @push.url_token + '-' + 'r'

    # Validate the passphrase
    if @push.passphrase == params[:passphrase]
      # Passphrase is valid
      # Set the passphrase cookie
      cookies[name] = { value: @push.passphrase_ciphertext, expires: 10.minutes.from_now }
      # Redirect to the payload
      redirect_to url_path(@push.url_token)
    else
      # Passphrase is invalid
      # Redirect to the passphrase page
      flash[:alert] = _('That passphrase is incorrect.  Please try again or contact the person or organization that sent you this link.')
      redirect_to passphrase_url_path(@push.url_token)
    end
  end

  # GET /urls/new
  def new
    if user_signed_in?
      @push = Url.new

      respond_to do |format|
        format.html # new.html.erb
      end
    else
      respond_to do |format|
        format.html { render template: 'urls/new_anonymous' }
      end
    end
  end

  api :POST, '/r.json', 'Create a new URL push.'
  param :url, Hash, "Push details", required: true do
    param :payload, String, desc: 'The URL encoded URL to redirect to.', required: true
    param :passphrase, String, desc: 'Require recipients to enter this passphrase to view the created push.'
    param :note, String, desc: 'If authenticated, the URL encoded note for this push.  Visible only to the push creator.', allow_blank: true
    param :expire_after_days, Integer, desc: 'Expire secret link and delete after this many days.'
    param :expire_after_views, Integer, desc: 'Expire secret link and delete after this many views.'
    param :retrieval_step, [true, false], desc: "Helps to avoid chat systems and URL scanners from eating up views."
  end
  formats ['json']
  example 'curl -X POST -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" --data "url[payload]=myurl&url[expire_after_days]=2&url[expire_after_views]=10" https://pwpush.com/r.json'
  def create
    # Require authentication if allow_anonymous is false
    # See config/settings.yml
    authenticate_user! if Settings.enable_logins && !Settings.allow_anonymous

    begin
      @push = Url.new(url_params)
    rescue ActionController::ParameterMissing => e
      @push = Url.new
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { "error": "No URL or note provided." }, status: :unprocessable_entity}
      end
      return
    end

    url_param = params.fetch(:url, {})
    payload_param = url_param.fetch(:payload, '')

    unless helpers.valid_url?(payload_param)
      msg = _('Invalid URL: Must have a valid URI scheme.')
      respond_to do |format|
        format.html {
          flash.now[:error] = msg
          render :new, status: :unprocessable_entity
        }
        format.json { render json: { "error": msg }, status: :unprocessable_entity }
      end
      return
    end

    @push.expire_after_days = params[:url].fetch(:expire_after_days, Settings.url.expire_after_days_default)
    @push.expire_after_views = params[:url].fetch(:expire_after_views, Settings.url.expire_after_views_default)
    @push.user_id = current_user.id if user_signed_in?
    @push.url_token = SecureRandom.urlsafe_base64(rand(8..14)).downcase

    create_detect_retrieval_step(@push, params)

    @push.payload = params[:url][:payload]
    @push.note = params[:url][:note] unless params[:url].fetch(:note, '').blank?
    @push.passphrase = params[:url].fetch(:passphrase, '')

    @push.validate!

    respond_to do |format|
      if @push.save
        format.html { redirect_to preview_url_path(@push) }
        format.json { render json: @push, status: :created }
      else
        format.html { render action: 'new', status: :unprocessable_entity }
        format.json { render json: @push.errors, status: :unprocessable_entity }
      end
    end
  end

  api :GET, '/r/:url_token/preview.json', 'Helper endpoint to retrieve the fully qualified secret URL of a push.'
  param :url_token, String, desc: 'Secret URL token of a previously created push.', :required => true
  formats ['json']
  example 'curl -X GET -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" https://pwpush.com/r/fk27vnslkd/preview.json'
  description ""
  def preview
    @push = Url.find_by_url_token!(params[:id])
    @secret_url = helpers.secret_url(@push)

    respond_to do |format|
      format.html { render action: 'preview' }
      format.json { render json: { url: @secret_url }, status: :ok }
    end

app/helpers/urls_helper.rb
require 'addressable/uri'

module UrlsHelper
  def valid_url?(url)
      parsed = Addressable::URI.parse(url) or return false
      !parsed.scheme.nil?
  rescue Addressable::URI::InvalidURIError
      false
  end
end
  

app/views/urls/active.html.erb
<% title(_('Active URL Pushes')) %>

<%= render partial: 'shared/dashboard_header' %>

<main>
  <% if @pushes.length.zero? %>
    <p class='text-center mt-3'>
      <%= _('You currently have no active URL pushes.') %>
    </p>
    <p class='text-center'>
      <%= link_to new_url_path, class: 'btn btn-primary' do %>
        <em class="bi bi-stars"></em>
        <%= _('Push a URL Now') %>
      <% end %>
    </p>
  <% else %>
    <div class="text-center my-3">
      <h1 class="display-6"><%= _('Active URL Pushes') %></h1>
    </div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top align-middle" aria-label='<%= _('Active Pushes') %>'>
      <thead>
      <tr>
          <th scope="col"><%= _('Push ID') %></th>
          <th scope="col"><%= _('Created') %></th>
          <th scope="col"><%= _('Note') %></th>
          <th scope="col" class="text-center"><%= _('Views') %></th>
          <th scope="col" class="text-center"><%= _('Days') %></th>
          <th scope="col" class="text-center"><em class='bi-tools'></em></th>
      </tr>
      </thead>
      <tbody class="table-group-divider">
      <% for push in @pushes do %>
        <tr>
          <td><%= push.url_token %></td>
          <td><%= I18n.l push.created_at, format: :long %></td>
          <td>
            <% if push.note.blank? %>
              <span class='text-muted'><%= _('None') %></span>
            <% else %>
              <div class="text-nowrap overflow-hidden">
                <%= push.note.truncate(30) %>
              </div>
            <% end %>
          </td>
          <td class="text-center"><%= "#{push.views.size}/#{push.expire_after_views}"%></td>
          <td class="text-center"><%= "#{push.days_old}/#{push.expire_after_days}"%></td>
          <td class="text-center">
            <div class="btn-group w-100" role="group" aria-label="<%= _('Push Controls') %>">
              <%= link_to preview_url_path(push), class: 'btn btn-primary btn-sm', rel: 'nofollow' do %>
                <%= _('Preview') %>
              <% end %>
              <%= link_to audit_url_path(push), class: 'btn btn-info btn-sm', rel: 'nofollow' do %>
                <%= _('Audit') %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @pushes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <% end %>
</main>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/expired.html.erb
<% title(_('Expired URL Pushes')) %>

<main>
  <%= render partial: 'shared/dashboard_header' %>
  <% if @pushes.length.zero? %>
    <p class='text-center mt-3'>
      <%= _('You currently have no expired URL pushes.') %>
    </p>
    <p class='text-center'>
      <%= link_to _('Push a URL Now'), new_url_path, class: 'btn btn-primary' %>
    </p>
  <% else %>
    <div class="text-center my-3">
      <h1 class="display-6"><%= _('Expired URL Pushes') %></h1>
    </div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top align-middle" aria-label='<%= _('Active Pushes') %>'>
      <thead>
      <tr>
          <th scope="col"><%= _('ID') %></th>
          <th scope="col"><%= _('Note') %></th>
          <th scope="col"><%= _('Expired On') %></th>
          <th scope="col" class="text-center"><em class='bi-tools'></em></th>
      </tr>
      </thead>
      <tbody class="table-group-divider">
      <% for push in @pushes do %>
        <tr>
          <td><%= push.url_token %></td>
          <td>
            <% if push.note.blank? %>
              <span class='text-muted'><%= _('None') %></span>
            <% else %>
              <div class="text-nowrap overflow-hidden">
                <%= push.note.truncate(30, omission: '...') %>
              </div>
            <% end %>
          </td>
          <td><%= I18n.l push.expired_on, format: :long %></td>
          <td class="text-center">
              <%= link_to audit_url_path(push), class: 'btn btn-info btn-sm', rel: 'nofollow' do %>
                <%= _('Audit Log') %>
              <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @pushes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <% end %>
</main>

app/views/urls/new.html.erb
<% title(_('Securely Send URLs')) %>

<div class='container'
    data-controller="knobs form"
    data-knobs-lang-day-value=<%= _('Day') %>
    data-knobs-lang-days-value=<%= _('Days') %>
    data-knobs-default-days-value=<%= Settings.url.expire_after_days_default %>

    data-knobs-lang-view-value=<%= _('View') %>
    data-knobs-lang-views-value=<%= _('Views') %>
    data-knobs-default-views-value=<%= Settings.url.expire_after_views_default %>

    data-knobs-default-retrieval-step-value=<%= Settings.url.retrieval_step_default %>

    data-knobs-ga-enabled-value=<%= ENV.key?('GA_ENABLE') %>
>
<%= render partial: "shared/topnav" %>

<%= form_for @push, data: { action: 'form#submit' } do |f| %>
    <div class='row'>
        <div class='col-sm-8'>
            <div class='row mb-3'>
                <div class='col'>
                    <div class="card">
                        <h5 class="card-header"><%= _('URL Redirection') %></h5>
                        <div class="card-body">
                            <div class="input-group">
                                <%= f.text_field(:payload, { class: "form-control",
                                                            placeholder: _('Enter the URL to redirect to...'),
                                                            autocomplete: "off",
                                                            spellcheck: "false",
                                                            autofocus: true,
                                                            required: true }) %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class='row'>
                <div><%= _('Expire secret link and delete after:') %></div>
                <div class='col-10'>
                    <%= range_field_tag("url_expire_after_days", Settings.url.expire_after_days_default,
                                        { :name => "url[expire_after_days]",
                                          :class => "form-range",
                                          :min => Settings.url.expire_after_days_min,
                                          :max => Settings.url.expire_after_days_max,
                                          :step => "1",
                                          "data-action" => "change->knobs#updateDaysSlider input->knobs#updateDaysSlider",
                                          "data-knobs-target" => "daysRange"
                                          })%>
                </div>
                <div class='col-2'>
                    <div class="form-text" data-knobs-target="daysRangeLabel"><%=Settings.url.expire_after_days_default %> <%= _('Days') %></div>
                </div>
            </div>

            <div class='row'>
                <div class='col-10'>
                    <%=range_field_tag("url_expire_after_views", Settings.url.expire_after_views_default,
                                       { :name => "url[expire_after_views]",
                                         :class => "form-range",
                                         :min => Settings.url.expire_after_views_min,
                                         :max => Settings.url.expire_after_views_max,
                                         :x_default => Settings.url.expire_after_views_default,
                                         :step => "1",
                                         "data-action" => "change->knobs#updateViewsSlider input->knobs#updateViewsSlider",
                                         "data-knobs-target" => "viewsRange"
                                         })%>
                </div>

                <div class='col-2'>
                    <div class="form-text" data-knobs-target="viewsRangeLabel"><%=Settings.url.expire_after_views_default %> <%= _('Views') %></div>
                </div>
            </div>
            <div class='row'>
                <div class='col'>
                    <p class='text-center form-text'><%= _('(whichever comes first)') %></p>
                </div>
            </div>

            <div class='row mb-3'>
                <div class='col'>
                    <div class="list-group mx-0">
                        <% if Settings.url.enable_retrieval_step %>
                            <label class="list-group-item d-flex gap-2">
                            <%=check_box_tag "url[retrieval_step]", nil, Settings.url.retrieval_step_default,
                                            { class: 'form-check-input flex-shrink-0',
                                            x_default: Settings.url.retrieval_step_default } %>
                            <span>
                                <%= _('Use a 1-click retrieval step') %>
                                <small class="d-block text-muted"><%= _('Helps to avoid chat systems and URL scanners from eating up redirects.') %></small>
                            </span>
                            </label>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class='row mb-3'>
                <div class='col'>
                    <div class="input-group">
                        <span class="input-group-text"><%= _('Passphrase Lockdown') %></span>
                        <%= f.text_field(:passphrase, { class: "form-control",
                                                        autocomplete: "off",
                                                        placeholder: _('Optional: Require recipients to enter a passphrase to view this push') }) %>
                    </div>
                </div>
            </div>
        </div>
        <div class='col'>
            <div class='row mb-3'>
                <div class="input-group">
                    <span class="input-group-text"><%= _('Reference Note') %></span>
                    <%= f.text_area(:note, { class: "form-control",
                                            rows: 1,
                                            placeholder: _('Optional'),
                                            autocomplete: "off" }) %>
                </div>
                <div class="form-text" id="basic-addon4"><%= _('Encrypted and visible only to you') %></div>
            </div>
            <div class='row my-3 px-5'> <hr/> </div>
            <div class='row mb-3'>
                <span class="text-muted">
                    <%= _('A secret URL will be generated that will redirect to the URL specified.') %>
                </span>
            </div>
            <div class='row mb-3'>
                <span class="text-muted">
                    <%= _('Upon expiration, the push URL will be deleted entirely.') %>
                    <%= _('An audit log of activity will be available.') %>
                </span>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col'>
            <p class='my-3'>
                <button class="form-control btn btn-primary" type="submit" data-form-target="pushit" data-disable-with="Pushing..."><%= _('Push It!') %></button>
            </p>
        </div>
    </div>
<% end %>
</div>

app/views/urls/new_anonymous.html.erb
<% title(_('Securely Share URLs')) %>

<div class='container'>
    <%= render partial: "shared/topnav" %>
    <div class="card text-center w-50 my-5 mx-auto">
        <div class="card-header">
            <em class="bi bi-send-check"></em>
            &nbsp;
            <%= _('Securely Send URLs That Expire Automatically') %>
        </div>
        <div class="card-body">
            <% if Settings.disable_signups %>
                <h5 class="card-title"><%= _('Please login to use this feature.') %></h5>
                <p class="card-text"></p>
                <a href="<%= new_user_session_path %>" class="btn btn-primary">Log In</a>
            <% else %>
                <h5 class="card-title"><%= _('Please login or sign up to use this feature.') %></h5>
                <p class="card-text"></p>
                <a href="<%= new_user_session_path %>" class="btn btn-primary">Log In</a>
                <a href="<%= new_user_registration_path %>" class="btn btn-success">Sign Up</a>
            <% end %>
        </div>
    </div>
</div>

app/views/urls/passphrase.html.erb
<% title(_('Enter The Secret Passphrase')) %>

<div class="container-fluid h-100">
  <div class="row d-flex justify-content-center align-items-center h-100 min-vh-100">
        <div class="col col-md-8">
            <div class="card">
                <form action="<%= access_url_path %>" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" name="passphrase" id="passphrase" autofocus="autofocus"
                      placeholder="<%= _('Enter the secret passphrase provided with this URL') %>" aria-label="<%= _('Enter the secret passphrase') %>" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit" id="button-addon2"><%= _('Go') %></button>
                </div>
                </form>
            </div>
        </div>
  </div>
</div>

app/views/urls/preliminary.html.erb
<div class="container h-100">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <p> <%=link_to _("Click Here to Proceed"), @secret_url %> </p>
    </div>
</div>

app/views/urls/preview.html.erb
<% title(_('Your Push Has Been Created')) %>

<div class="container h-75">
    <div class="d-flex flex-column justify-content-center align-items-center">

      <h2 class='mt-5'><%= _('Your push has been created.') %></h2>

      <p class='mt-5'><%= _('Use this secret link to share it:') %></p>
      <%= render partial: 'shared/secret_url_bar' %>

      <p class='mb-5'>
        <%= _('This push will expire after') %>
        <strong><%=@push.expire_after_days%> <%= n_('day', 'days', @push.expire_after_days) %></strong>
        <%= _('or') %>
        <strong><%=@push.expire_after_views%> <%= n_('view', 'views', @push.expire_after_views) %></strong>
        <%= _('(whichever comes first)') %>.
      </p>

      <% if @push.retrieval_step == true %>
        <p class='mb-5'><%= _('It also includes a') %> <strong><%= _('1-click preliminary retrieval step') %></strong>.  </p>
      <% end %>

      <p class='mb-5'>
        <%=link_to _('View This Push Now'), @secret_url %> <%= _('(will burn a view) or') %>
        <%=link_to _('Push Another'), new_url_path %>
      </p>

      <% if user_signed_in? %>
        <%= link_to audit_url_path(@push), class: 'btn btn-secondary btn-sm', rel: 'nofollow' do %>
          <em class='bi-card-list'></em> <%= _('View Audit Log') %>
        <% end %>
      <% end %>

      <p class='mt-5 small'>
        <%= _('Tip: Pushing to an international user?  Change the secret link language using the dropdown menu to the right of the URL.') %>
      </p>
  </div>
</div>