config/routes.rb
Rails.application.routes.draw do
  routes_config = Proc.new {
    if ENV.key?('PWPUSH_COM')
      match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
    end

    localized do
      apipie
      devise_for :users, skip: :registrations, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations'
      }

      if Settings.disable_signups
        allowed_reg_routes = %i[edit update]
      else
        allowed_reg_routes = %i[new create edit update]
      end

      devise_scope :user do
        resource  :registration,
                  only: allowed_reg_routes,
                  path: 'users',
                  path_names: { new: 'sign_up' },
                  controller: 'users/registrations',
                  as: :user_registration do
                    get :cancel
                    get :token
                    delete :token, action: :regen_token
                  end
      end

      # Dashboard controller has been removed.  Maintain this remapping for now.
      get '/d/active', to: 'passwords#active'
      get '/d/expired', to: 'passwords#expired'

      resources :p, controller: :passwords, as: :passwords, except: %i[index edit update] do
        get 'preview', on: :member
        get 'passphrase', on: :member
        post 'access', on: :member
        get 'r', on: :member, as: 'preliminary', action: 'preliminary'
        get 'audit', on: :member
        get 'active', on: :collection
        get 'expired', on: :collection
      end

      # File pushes only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_file_pushes
        resources :f, controller: :file_pushes, as: :file_pushes, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      # URL based pushes can only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_url_pushes
        resources :r, controller: :urls, as: :urls, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      resources :c, controller: :commands, as: :commands, allow: %i[create]
      # get '/slack_direct_install', to: redirect("https://slack.com/oauth/authorize?client_id=#{SLACK_CLIENT_ID}&scope=commands", status: 302)
      get '/pages/*id' => 'pages#show', as: :page, format: false
      resources :feedbacks, only: %i[new create]
      root to: 'passwords#new'
    end
  }

  # This allows for running the application in a subfolder.  See config/settings.yml (relative_root)
  if Settings.relative_root
    scope("#{Settings.relative_root}/:locale") do
      routes_config.call
    end
    # Remap the root to the default locale
    get Settings.relative_root, to: redirect("/#{Settings.relative_root}/#{I18n.default_locale}", status: 302)
  else
    routes_config.call
  end
end

app/views/shared/_alerts.html.erb
<% # !alert.include?("translation missing") %>
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show my-3" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show my-3" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if info %>
  <div class="alert alert-info alert-dismissible fade show my-3" role="alert">
    <%= info %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if error %>
  <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
    <%= error %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if success %>
  <div class="alert alert-success alert-dismissible fade show my-3" role="alert">
    <%= success %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if warning %>
  <div class="alert alert-warning alert-dismissible fade show my-3" role="alert">
    <%= warning %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_copy_button.html.erb
<button class='btn btn-primary' data-action="click->copy#copyToClipboard">
    <em class="bi bi-clipboard-check"></em> <%= _('Copy to Clipboard') %>
</button>

app/views/shared/_dashboard_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-3 mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">📊 <%= _('Dashboard') %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to _('Passwords'), active_passwords_path, class: "nav-link #{ 'active text-decoration-underline' if current_controller?('passwords') }" %>
        </li>
        <% if Settings.enable_file_pushes %>
          <li class="nav-item">
            <%= link_to _('Files'), active_file_pushes_path, class: "nav-link #{ 'active text-decoration-underline' if current_controller?('file_pushes') }" %>
          </li>
        <% end %>
        <% if Settings.enable_url_pushes %>
          <li class="nav-item">
            <%= link_to _('URLs'), active_urls_path, class: "nav-link #{ 'active text-decoration-underline' if current_controller?('urls') }" %>
          </li>
        <% end %>
      </ul>
      <div class="btn-group">
        <% if current_controller?('passwords') %>
            <%= link_to _('Active'), active_passwords_path, class: "btn btn-primary #{ 'active' if current_page?(active_passwords_path) }" %>
            <%= link_to _('Expired'), expired_passwords_path, class: "btn btn-primary #{ 'active' if current_page?(expired_passwords_path) }" %>
        <% elsif current_controller?('file_pushes') %>
            <%= link_to _('Active'), active_file_pushes_path, class: "btn btn-primary #{ 'active' if current_page?(active_file_pushes_path) }" %>
            <%= link_to _('Expired'), expired_file_pushes_path, class: "btn btn-primary #{ 'active' if current_page?(expired_file_pushes_path) }" %>
        <% elsif current_controller?('urls') %>
            <%= link_to _('Active'), active_urls_path, class: "btn btn-primary #{ 'active' if current_page?(active_urls_path) }" %>
            <%= link_to _('Expired'), expired_urls_path, class: "btn btn-primary #{ 'active' if current_page?(expired_urls_path) }" %>
        <% end%>
      </div>
      <% if current_controller?('passwords') %>
            <%= link_to _('New'), new_password_path, class: "btn btn-success ms-3" %>
      <% elsif current_controller?('file_pushes') %>
            <%= link_to _('New'), new_file_push_path, class: "btn btn-success ms-3" %>
      <% elsif current_controller?('urls') %>
            <%= link_to _('New'), new_url_path, class: "btn btn-success ms-3" %>
      <% end%>
    </div>
  </div>
</nav>

app/views/shared/_email_footer.html.erb
<p>
-- 
<br/>
<%= link_to Settings.brand.title, root_url %>
<br/>
<span class="fs-6 text-muted"><%= Settings.brand.tagline %></span>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-5 mb-0 text-muted">&copy; 2023 <%= _('Peter') %> Giacomo Lombardo</p>

      <%= link_to root_path(locale: locale.to_s), class: "col-md-2 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" do %>
        <picture>
          <% if Settings.brand.nil? || Settings.brand.light_logo.nil? %>
            <source srcset="<%= asset_path('logo-transparent-sm-bare.png') %>" media="(prefers-color-scheme: light) or (prefers-color-scheme: no-preference)">
            <source srcset="<%= asset_path('logo-transparent-sm-dark-bare.png') %>" media="(prefers-color-scheme: dark)">
            <img src="<%= asset_path('logo-transparent-sm-bare.png') %>" alt="<%= _('Password Pusher Logo') %>" style='height: 40px;' />
          <% else %>
            <source srcset="<%= Settings.brand.light_logo %>" media="(prefers-color-scheme: light) or (prefers-color-scheme: no-preference)">
            <source srcset="<%= Settings.brand.dark_logo %>" media="(prefers-color-scheme: dark)">
            <img src="<%= Settings.brand.light_logo %>" alt="<%= _('Password Pusher Logo') %>" style='height: 40px;' />
          <% end %>
        </picture>
      <% end %>

      <% if Settings.brand.show_footer_menu %>
        <ul class="nav col-md-5 justify-content-end">
          <li class="nav-item"><%= link_to _('Front Page'), root_path(locale: locale.to_s), class: 'nav-link px-2 text-muted' %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle px-2 text-muted" href="#" id="resourcesDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= _('Resources') %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="resourcesDropdownMenuLink">
              <li class="dropdown-item">
                <%= link_to 'https://hub.docker.com/u/pglombardo', class: 'nav-link px-2 text-muted', target: '_blank' do %>
                  <%= _('Docker Containers') %>
                  <em class="bi bi-box-arrow-up-right ms-2"></em>
                <% end %>
              </li>
              <li class="dropdown-item"><%= link_to _('FAQ'), page_path('faq'), class: 'nav-link px-2 text-muted' %></li>
              <li class="dropdown-item"><%= link_to _('JSON API'), apipie_apipie_path, class: 'nav-link px-2 text-muted' %></li>
              <li class="dropdown-item"><%= link_to _('Key Generator'), page_path('generate_key'), class: 'nav-link px-2 text-muted' %></li>
              <li class="dropdown-item">
                <%= link_to 'https://github.com/pglombardo/PasswordPusher', class: 'nav-link px-2 text-muted', target: '_blank' do %>
                  <%= _('Source Code') %>
                  <em class="bi bi-box-arrow-up-right ms-2"></em>
                <% end %>
              </li>
              <li class="dropdown-item"><%= link_to _('Tools'), page_path('tools'), class: 'nav-link px-2 text-muted' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle px-2 text-muted" href="#" id="aboutDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= _('About') %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="aboutDropdownMenuLink">
              <li class="dropdown-item"><%= link_to _('Overview'), page_path('about'), class: 'nav-link px-2 text-muted' %></li>
              <li class="dropdown-item"><%= link_to _('Help Translate!'), page_path('translate'), class: 'nav-link px-2 text-muted' %></li>
              <li class="dropdown-item"><%= link_to _('Send Feedback'), new_feedback_path, class: 'nav-link px-2 text-muted' %></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <%= link_to root_path(locale: locale.to_s), class: 'd-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none', hreflang: locale.to_s do %>
      <div class='me-2'>
      <picture>
        <% if Settings.brand.nil? || Settings.brand.light_logo.nil? %>
          <source srcset="<%= asset_path('logo-transparent-sm-bare.png') %>" media="(prefers-color-scheme: light) or (prefers-color-scheme: no-preference)">
          <source srcset="<%= asset_path('logo-transparent-sm-dark-bare.png') %>" media="(prefers-color-scheme: dark)">
          <img src="<%= asset_path('logo-transparent-sm-bare.png') %>" alt="<%= _('Password Pusher Logo') %>" style='height: 50px;' />
        <% else %>
          <source srcset="<%= Settings.brand.light_logo %>" media="(prefers-color-scheme: light) or (prefers-color-scheme: no-preference)">
          <source srcset="<%= Settings.brand.dark_logo %>" media="(prefers-color-scheme: dark)">
          <img src="<%= Settings.brand.light_logo %>" alt="<%= _('Password Pusher Logo') %>" style='height: 50px;' />
        <% end %>
      </picture>
      </div>
      <div>
        <span class="fs-4 display-1"><%= Settings.brand.title %></span>
        <br/>
        <span class="fs-6 text-muted"><%= Settings.brand.tagline %></span>
      </div>
    <% end %>

      <ul class="nav nav-pills align-items-center">
        <% if Settings.enable_logins %>
          <% if current_user %>
            <li class="nav-item lead">
              <%= link_to active_passwords_path, class: "btn btn-primary" do %>
                <em class='bi bi-clipboard-data'></em>
                <%= _('Dashboard') %>
              <% end %>

            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="accountDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <em class='bi-file-person'></em>
                <%= _('Account') %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="accountDropdownMenuLink">
                <li>
                  <%= link_to _('Edit Login Details'), edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to _('API Token'), token_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to _('Log Out'), destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to _('Log In'), new_user_session_path, class: "nav-link lead" %>
            </li>
            <% if !Settings.disable_signups %>
              <li class="nav-item">
                <%= link_to _('Sign Up'), new_user_registration_path, class: "nav-link lead" %>
              </li>
            <% end %>
          <% end %>
        <% end %>
        <li class="nav-item">
          <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#languageModal">
            <em class='bi-translate'></em>
            <%= _('Language') %>
          </button>
        </li>
      </ul>


    <%= render partial: 'shared/lang_selector_modal' %>
  </header>
</div>

app/views/shared/_lang_selector_modal.erb
<!-- Language Selector Modal -->
<div class="modal fade" id="languageModal" tabindex="-1" aria-labelledby="languageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="languageModalLabel"><%= _('Select your language') %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% if Settings.language_codes %>
          <% I18n.available_locales.each_slice(4) do |group| %>
            <div class="row">
            <% group.each do |lang| %>
                <div class="col-3 m-0 p-0">
                  <div class="card text-center">
                    <div class="card-body p-1">
                      <p class="card-text">
                          <%= link_to url_for(locale: lang.to_s), hreflang: lang.to_s, rel: 'alternate', class: "nav-link text-muted" do %>
                            <em class="fi fi-<%= Settings.country_codes[lang] %>"></em>
                            <br/>
                            <%= Settings.language_codes[lang] %>
                          <% end %>
                      </p>
                    </div>
                  </div>
                </div>
            <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_layout_icons.html.erb
<% if Settings.brand.icon_57x57 %>
  <link rel="apple-touch-icon" sizes="57x57" href="<%=Settings.brand.icon_57x57%>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%=Settings.brand.icon_60x60%>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%=Settings.brand.icon_72x72%>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%=Settings.brand.icon_76x76%>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%=Settings.brand.icon_114x114%>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%=Settings.brand.icon_120x120%>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%=Settings.brand.icon_144x144%>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%=Settings.brand.icon_152x152%>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%=Settings.brand.icon_180x180%>">
  <link rel="icon" type="image/png" sizes="192x192"  href="<%=Settings.brand.icon_192x192%>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%=Settings.brand.icon_32x32%>">
  <link rel="icon" type="image/png" sizes="96x96" href="<%=Settings.brand.icon_96x96%>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%=Settings.brand.icon_16x16%>">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="<%=Settings.brand.ms_icon_144x144%>">
  <meta name="theme-color" content="#ffffff">
<% else %>
  <link rel="apple-touch-icon" sizes="57x57" href="<%=asset_path('apple-icon-57x57.png')%>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%=asset_path('apple-icon-60x60.png')%>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%=asset_path('apple-icon-72x72.png')%>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%=asset_path('apple-icon-76x76.png')%>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%=asset_path('apple-icon-114x114.png')%>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%=asset_path('apple-icon-120x120.png')%>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%=asset_path('apple-icon-144x144.png')%>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%=asset_path('apple-icon-152x152.png')%>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%=asset_path('apple-icon-180x180.png')%>">
  <link rel="icon" type="image/png" sizes="192x192"  href="<%=asset_path('android-icon-192x192.png')%>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%=asset_path('favicon-32x32.png')%>">
  <link rel="icon" type="image/png" sizes="96x96" href="<%=asset_path('favicon-96x96.png')%>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%=asset_path('favicon-16x16.png')%>">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="<%=asset_path('ms-icon-144x144.png')%>">
  <meta name="theme-color" content="#ffffff">
<% end %>

app/views/shared/_newsletter_sign_up.html.erb
<div class="card mb-3">
    <h5 class="card-header"><em class="bi bi-envelope"></em> <%= _('Get The Newsletter') %></h5>
    <div class="card-body">
        <p><%= _('Updates on big releases, security issues, features, integrations, tips and more.') %></p>
        <form
        action="https://buttondown.email/api/emails/embed-subscribe/pwpush"
        method="post"
        target="popupwindow"
        onsubmit="window.open('https://buttondown.email/pwpush', 'popupwindow')"
        class="embeddable-buttondown-form"
        >
        <input type="hidden" name="tag" value="pwpush.com">
        <input type="email" class="form-control mb-3" name="email" id="bd-email" placeholder="<%= _("Enter your email...") %>"/>
        <input type="submit" class="form-control btn btn-primary" value="<%= _("Subscribe") %>" />
        </form>
    </div>
</div>

app/views/shared/_pw_generator_modal.html.erb
<div class="modal fade" id="configureModal" tabindex="-1" aria-labelledby="configureModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="configureModalLabel"><%= _('Configure Password Generation') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class='display-6 p-3 mb-3 text-center text-break text-wrap border'
            id='configure_password_payload' data-pwgen-target="testPayloadArea">
        <%= _('Test Area') %>
        </div>
        <div class="row">
            <div class="col">
                <div class="mb-3">
                    <label for="num_syllables" class="form-label"><%= _('Number of Syllables') %></label>
                    <input type="number" class="form-control" id="num_syllables" data-pwgen-target="numSyllablesInput">
                </div>
                <div class="mb-3">
                    <label for="min_syllable_length" class="form-label"><%= _('Minimum Syllable Length') %></label>
                    <input type="number" class="form-control" id="min_syllable_length" data-pwgen-target="minSyllableLengthInput">
                </div>
                <div class="mb-3">
                    <label for="max_syllable_length" class="form-label"><%= _('Maximum Syllable Length') %></label>
                    <input type="number" class="form-control" id="max_syllable_length" data-pwgen-target="maxSyllableLengthInput">
                </div>
            </div>
            <div class="col">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="include_numbers" data-pwgen-target="includeNumbersCheckbox">
                    <label class="form-check-label" for="include_numbers"><%= _('Include numbers') %></label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="use_titlecase"  data-pwgen-target="useTitleCaseCheckbox" checked>
                    <label class="form-check-label" for="use_titlecase"><%= _('Use Titlecase') %></label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="use_separators" data-pwgen-target="useSeparatorsCheckbox" checked>
                    <label class="form-check-label" for="use_separators"><%= _('Use Separators') %></label>
                </div>
                <div class="d-grid gap-2 m-3 mt-5">
                    <button class="btn btn-primary" type="button" id='configure_generate_password'
                        data-action="click->pwgen#testGenerate"><%= _('Test') %></button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="mb-3 row">
                    <label for="separators" class="col-sm-3 col-form-label"><%= _('Separators') %></label>
                    <div class="col-sm-8">
                        <input class="form-control" type="text" id='separators' aria-label="Separators" data-pwgen-target="separatorsInput">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="vowels" class="col-sm-3 col-form-label"><%= _('Vowels') %></label>
                    <div class="col-sm-8">
                        <input class="form-control" type="text" id='vowels' aria-label="Vowels" data-pwgen-target="vowelsInput">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="consonants" class="col-sm-3 col-form-label"><%= _('Consonants') %></label>
                    <div class="col-sm-8">
                        <input class="form-control" type="text" id='consonants' aria-label="Consonants" data-pwgen-target="consonantsInput">
                    </div>
                </div>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id='reset_to_defaults' data-action="click->pwgen#resetSettings"><%= _('Reset to Defaults') %></button>
        <button type="button" class="btn btn-primary" id='save_configure' data-bs-dismiss="modal" data-action="click->pwgen#saveSettings"><%= _('Save') %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_secret_url_bar.html.erb
<div class='input-group mb-5 w-75' data-controller="copy">
    <input class='form-control', id='secret_url' value='<%= @secret_url %>' spellcheck='false' readonly='true' data-copy-target="payloadDiv">
    <% if Settings.language_codes %>
        <button type="button" class="btn btn-primary">
            <em class="me-2 fi fi-<%= Settings.country_codes[params["push_locale"] || I18n.locale] %>"></em>
            <%= Settings.language_codes[params["push_locale"] || I18n.locale] %>
        </button>
    <% end %>
    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu">
        <li><span class="dropdown-item-text"><%= _('Secret Link Language') %></span></li>
        <li><hr class="dropdown-divider"></li>
        <% if Settings.language_codes %>
            <% I18n.available_locales.each do |lang| %>
                <li class='dropdown-item'>
                    <%= link_to url_for(push_locale: lang), class: "nav-link p-0 m-0 text-muted" do %>
                        <em class="me-2 fi fi-<%= Settings.country_codes[lang] %>"></em>
                        <%= Settings.language_codes[lang] %>
                    <% end %>
                </li>
            <% end %>
        <% end %>
    </ul>
    <button class='input-group-text btn-success' data-action="click->copy#miniCopyToClipboard" alt="<%= _('Copy to Clipboard') %>">
        <em class="bi bi-clipboard-check"></em>
    </button>
</div>

app/views/shared/_topnav.html.erb
<% if Settings.enable_logins %>
  <ul class="nav nav-tabs mb-3">
    <li class="nav-item">
      <a class="nav-link <%= current_controller?("passwords") ? 'active' : '' %>" aria-current="page" href="<%= new_password_path %>"><%= _('Passwords') %></a>
    </li>
    <% if Settings.enable_file_pushes %>
      <li class="nav-item">
        <a class="nav-link <%= current_controller?("file_pushes") ? 'active' : '' %>" href="<%= new_file_push_path %>"><%= _('Files') %></a>
      </li>
    <% end %>
    <% if Settings.enable_url_pushes %>
      <li class="nav-item">
        <a class="nav-link <%= current_controller?("urls") ? 'active' : '' %>" aria-current="page" href="<%= new_url_path %>"><%= _('URLs') %></a>
      </li>
    <% end %>
  </ul>
<% end %>