config/routes.rb
Rails.application.routes.draw do
  routes_config = Proc.new {
    if ENV.key?('PWPUSH_COM')
      match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
    end

    localized do
      apipie
      devise_for :users, skip: :registrations, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations'
      }

      if Settings.disable_signups
        allowed_reg_routes = %i[edit update]
      else
        allowed_reg_routes = %i[new create edit update]
      end

      devise_scope :user do
        resource  :registration,
                  only: allowed_reg_routes,
                  path: 'users',
                  path_names: { new: 'sign_up' },
                  controller: 'users/registrations',
                  as: :user_registration do
                    get :cancel
                    get :token
                    delete :token, action: :regen_token
                  end
      end

      # Dashboard controller has been removed.  Maintain this remapping for now.
      get '/d/active', to: 'passwords#active'
      get '/d/expired', to: 'passwords#expired'

      resources :p, controller: :passwords, as: :passwords, except: %i[index edit update] do
        get 'preview', on: :member
        get 'passphrase', on: :member
        post 'access', on: :member
        get 'r', on: :member, as: 'preliminary', action: 'preliminary'
        get 'audit', on: :member
        get 'active', on: :collection
        get 'expired', on: :collection
      end

      # File pushes only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_file_pushes
        resources :f, controller: :file_pushes, as: :file_pushes, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      # URL based pushes can only enabled when logins are enabled.
      if Settings.enable_logins && Settings.enable_url_pushes
        resources :r, controller: :urls, as: :urls, except: %i[index edit update] do
          get 'preview', on: :member
          get 'passphrase', on: :member
          post 'access', on: :member
          get 'r', on: :member, as: 'preliminary', action: 'preliminary'
          get 'audit', on: :member
          get 'active', on: :collection
          get 'expired', on: :collection
        end
      end

      resources :c, controller: :commands, as: :commands, allow: %i[create]
      # get '/slack_direct_install', to: redirect("https://slack.com/oauth/authorize?client_id=#{SLACK_CLIENT_ID}&scope=commands", status: 302)
      get '/pages/*id' => 'pages#show', as: :page, format: false
      resources :feedbacks, only: %i[new create]
      root to: 'passwords#new'
    end
  }

  # This allows for running the application in a subfolder.  See config/settings.yml (relative_root)
  if Settings.relative_root
    scope("#{Settings.relative_root}/:locale") do
      routes_config.call
    end
    # Remap the root to the default locale
    get Settings.relative_root, to: redirect("/#{Settings.relative_root}/#{I18n.default_locale}", status: 302)
  else
    routes_config.call
  end
end

app/models/file_push.rb
class FilePush < ApplicationRecord
  has_many :views, dependent: :destroy
  has_encrypted :payload, :note, :passphrase
  
  has_many_attached :files

  belongs_to :user
  
  def to_param
    url_token.to_s
  end

  def days_old
    (Time.now.to_datetime - created_at.to_datetime).to_i
  end

  def days_remaining
    [(expire_after_days - days_old), 0].max
  end

  def views_remaining
    [(expire_after_views - view_count), 0].max
  end

  def view_count
    views.where(kind: 0).size
  end

  def successful_views
    views.where(successful: true, kind: 0).order(:created_at)
  end

  def failed_views
    views.where(successful: false, kind: 0).order(:created_at)
  end

  # Expire this password, delete the password and save the record
  def expire
    self.expired = true
    self.payload = nil
    self.passphrase = nil
    self.expired_on = Time.now
    self.files.purge
    save
  end

  # Override to_json so that we can add in <days_remaining>, <views_remaining>
  # and show the clear password
  def to_json(*args)
  # def to_json(owner: false, payload: false)
    attr_hash = attributes

    owner = false
    payload = false

    owner = args.first[:owner] if args.first.key?(:owner)
    payload = args.first[:payload] if args.first.key?(:payload)

    attr_hash['days_remaining'] = days_remaining
    attr_hash['views_remaining'] = views_remaining

    file_list = {}
    files.each do |file|
      # FIXME: default host?
      file_list[file.filename] = Rails.application.routes.url_helpers.rails_blob_url(file, only_path: true)
    end
    attr_hash['files'] = file_list.to_json

    # Remove unnecessary fields
    attr_hash.delete('payload_ciphertext')
    attr_hash.delete('note_ciphertext')
    attr_hash.delete('passphrase_ciphertext')
    attr_hash.delete('user_id')
    attr_hash.delete('id')

    attr_hash.delete('passphrase')
    attr_hash.delete('note') unless owner
    attr_hash.delete('payload') unless payload

    Oj.dump attr_hash
  end

  ##
  # validate!
  #
  # Run basic validations on the password.  Expire the password
  # if it's limits have been reached (time or views)
  #
  def validate!
    return if expired

    # Range checking
    self.expire_after_days  ||= Settings.files.expire_after_days_default
    self.expire_after_views ||= Settings.files.expire_after_views_default

    unless expire_after_days.between?(Settings.files.expire_after_days_min, Settings.files.expire_after_days_max)
      self.expire_after_days = Settings.files.expire_after_days_default
    end

    unless expire_after_views.between?(Settings.files.expire_after_views_min, Settings.files.expire_after_views_max)
      self.expire_after_views = Settings.files.expire_after_views_default
    end

    return if new_record?

    expire if !days_remaining.positive? || !views_remaining.positive?
  end
end

app/controllers/file_pushes_controller.rb
require 'securerandom'

class FilePushesController < ApplicationController
  helper FilePushesHelper

  # Authentication always except for :show
  acts_as_token_authentication_handler_for User, except: [:show, :new, :preliminary, :destroy, :passphrase, :access]

  resource_description do
    name 'File Pushes'
    short 'Interact directly with file pushes.  This feature (and corresponding API) is currently in beta.'
  end

  api :GET, '/f/:url_token.json', 'Retrieve a file push.'
  param :url_token, String, desc: 'Secret URL token of a previously created push.', :required => true
  formats ['json']
  example 'curl -X GET -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" https://pwpush.com/f/fk27vnslkd.json'
  description "Retrieves a push including it's payload and details.  If the push is still active, this will burn a view and the transaction will be logged in the push audit log."
  def show
    redirect_to :root && return unless params.key?(:id)

    begin
      @push = FilePush.includes(:views).find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      # Old, expired & anonymous pushes have no value to anybody.
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'file_pushes/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    # This file_push may have expired since the last view.  Validate the file_push
    # expiration before doing anything.
    @push.validate!

    if @push.expired
      log_view(@push)
      respond_to do |format|
        format.html { render template: 'file_pushes/show_expired', layout: 'naked' }
        format.json { render json: @push.to_json(payload: true) }
      end
      return
    else
      @payload = @push.payload
    end

    # Passphrase handling
    if !@push.passphrase.nil? && !@push.passphrase.blank?
      # Construct the passphrase cookie name
      name = @push.url_token + '-' + 'f'

      # The passphrase can be passed in the params or in the cookie (default)
      # JSON requests must pass the passphrase in the params
      has_passphrase = params.fetch(:passphrase, nil) == @push.passphrase || cookies[name] == @push.passphrase_ciphertext

      if !has_passphrase
        # Passphrase hasn't been provided or is incorrect
        # Redirect to the passphrase page
        respond_to do |format|
          format.html { redirect_to passphrase_file_push_path(@push.url_token) }
          format.json { render json: { error: "This push has a passphrase that was incorrect or not provided." } }
        end
        return
      end

      # Delete the cookie
      cookies.delete name
    end


    log_view(@push)
    expires_now

    # Optionally blur the text payload
    @blur_css_class = Settings.files.enable_blur ? 'spoiler' : ''

    respond_to do |format|
      format.html { render layout: 'bare' }
      format.json { render json: @push.to_json(payload: true) }
    end

    # We can't expire in this case because the attached files would be deleted and
    # downloading wouldn't work.
    # TODO: ActiveJob delete in 15 minutes after last view is shown.
    # # Expire if this is the last view for this push
    # @push.expire if !@push.views_remaining.positive?
  end

  # GET /f/:url_token/passphrase
  def passphrase
    begin
      @push = FilePush.find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      #
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      #
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'file_pushes/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    respond_to do |format|
      format.html { render action: 'passphrase', layout: 'naked' }
    end
  end

  # POST /f/:url_token/access
  def access
    begin
      @push = FilePush.find_by_url_token!(params[:id])
    rescue ActiveRecord::RecordNotFound
      # Showing a 404 reveals that this Secret URL never existed
      # which is an information leak (not a secret anymore)
      #
      # We also don't want data in general. We entirely delete old pushes that:
      # 1. have expired (payloads already deleted long ago)
      # 2. are anonymous/not linked to a user account (audit log not needed)
      #
      # When not found, show the 'expired' page so even very old secret URLs
      # when clicked they will be accurate - this secret URL has expired.
      # No easy fix for JSON unfortunately as we don't have a record to show.
      respond_to do |format|
        format.html { render template: 'file_pushes/show_expired', layout: 'naked' }
        format.json { render json: { error: 'not-found' }.to_json, status: 404 }
      end
      return
    end

    # Construct the passphrase cookie name
    name = @push.url_token + '-' + 'f'

    # Validate the passphrase
    if @push.passphrase == params[:passphrase]
      # Passphrase is valid
      # Set the passphrase cookie
      cookies[name] = { value: @push.passphrase_ciphertext, expires: 10.minutes.from_now }
      # Redirect to the payload
      redirect_to file_push_path(@push.url_token)
    else
      # Passphrase is invalid
      # Redirect to the passphrase page
      flash[:alert] = _('That passphrase is incorrect.  Please try again or contact the person or organization that sent you this link.')
      redirect_to passphrase_file_push_path(@push.url_token)
    end
  end

  # GET /file_pushes/new
  def new
    if user_signed_in?
      @push = FilePush.new

      respond_to do |format|
        format.html # new.html.erb
      end
    else
      respond_to do |format|
        format.html { render template: 'file_pushes/new_anonymous' }
      end
    end
  end

  api :POST, '/f.json', 'Create a new file push.'
  param :file_push, Hash, "Push details", required: true do
    param :payload, String, desc: 'The URL encoded secret text to share.', required: true
    param :passphrase, String, desc: 'Require recipients to enter this passphrase to view the created push.'
    param :note, String, desc: 'If authenticated, the URL encoded note for this push.  Visible only to the push creator.', allow_blank: true
    param :expire_after_days, Integer, desc: 'Expire secret link and delete after this many days.'
    param :expire_after_views, Integer, desc: 'Expire secret link and delete after this many views.'
    param :deletable_by_viewer, [true, false], desc: "Allow users to delete the push once retrieved."
    param :retrieval_step, [true, false], desc: "Helps to avoid chat systems and URL scanners from eating up views."
  end
  formats ['json']
  example 'curl -X POST -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" -F "file_push[files][]=@/path/to/file/file1.extension" -F "file_push[files][]=@/path/to/file/file2.extension" https://pwpush.com/f.json'
  def create
    # Require authentication if allow_anonymous is false
    # See config/settings.yml
    authenticate_user! if Settings.enable_logins && !Settings.allow_anonymous

    @push = FilePush.new

    # params[:file_push] has to exist
    # params[:file_push] has to be a ActionController::Parameters (Hash)
    file_push_param = params.fetch(:file_push, {})
    if !file_push_param.respond_to?(:fetch)
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { "error": "No password, text or files provided." }, status: :unprocessable_entity }
      end
      return
    end

    # params[:file_push][:payload] must have a length between 1 and 1 megabyte
    payload_param = file_push_param.fetch(:payload, '')
    files_param   = file_push_param.fetch(:files, [])
    unless (payload_param.is_a?(String) && payload_param.length.between?(1, 1.megabyte)) || !files_param.empty? || files_param.size > 10
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { "error": "No password, text or files provided." }, status: :unprocessable_entity }
      end
      return
    end

    @push_count = FilePush.where(user_id: current_user.id, expired: false).count
    if @push_count >= 10
      msg = _('Only 10 active file pushes allowed while in Beta and until things are stable. If it\'s an option, you can manually expire existing pushes before creating new ones.')
      respond_to do |format|
        format.html {
          flash.now[:warning] = msg
          render :new, status: :unprocessable_entity
        }
        format.json { render json: { "error": msg }, status: :unprocessable_entity }
      end
      return
    end

    @push.expire_after_days = params[:file_push].fetch(:expire_after_days, Settings.files.expire_after_days_default)

app/helpers/file_pushes_helper.rb
module FilePushesHelper
  def filesize(size)
      units = %w[B KiB MiB GiB TiB Pib EiB ZiB]

      return '0.0 B' if size == 0
      exp = (Math.log(size) / Math.log(1024)).to_i
      exp += 1 if (size.to_f / 1024 ** exp >= 1024 - 0.05)
      exp = units.size - 1 if exp > units.size - 1

      '%.1f %s' % [size.to_f / 1024 ** exp, units[exp]]
  end
end
  

app/views/file_pushes/active.html.erb
<% title(_('Active File Pushes')) %>

<%= render partial: 'shared/dashboard_header' %>

<main>
  <% if @pushes.length.zero? %>
    <p class='text-center mt-3'>
      <%= _('You currently have no active file pushes.') %>
    </p>
    <p class='text-center'>
      <%= link_to new_file_push_path, class: 'btn btn-primary' do %>
        <em class="bi bi-stars"></em>
        <%= _('Push Some Files Now') %>
      <% end %>
    </p>
  <% else %>
    <div class="text-center my-3">
      <h1 class="display-6"><%= _('Active File Pushes') %></h1>
    </div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top align-middle" aria-label='<%= _('Active Pushes') %>'>
      <thead>
      <tr>
          <th scope="col"><%= _('Push ID') %></th>
          <th scope="col"><%= _('Created') %></th>
          <th scope="col"><%= _('Note') %></th>
          <th scope="col" class="text-center"><%= _('File Count') %></th>
          <th scope="col" class="text-center"><%= _('Views') %></th>
          <th scope="col" class="text-center"><%= _('Days') %></th>
          <th scope="col" class="text-center"><em class='bi-tools'></em></th>
      </tr>
      </thead>
      <tbody class="table-group-divider">
      <% for push in @pushes do %>
        <tr>
          <td><%= push.url_token %></td>
          <td><%= I18n.l push.created_at, format: :long %></td>
          <td>
            <% if push.note.blank? %>
              <span class='text-muted'><%= _('None') %></span>
            <% else %>
              <div class="text-nowrap overflow-hidden">
                <%= push.note.truncate(30) %>
              </div>
            <% end %>
          </td>
          <td class="text-center"><%= "#{push.files.size}" %></td>
          <td class="text-center"><%= "#{push.views.size}/#{push.expire_after_views}"%></td>
          <td class="text-center"><%= "#{push.days_old}/#{push.expire_after_days}"%></td>
          <td class="text-center">
            <div class="btn-group w-100" role="group" aria-label="<%= _('Push Controls') %>">
              <%= link_to preview_file_push_path(push), class: 'btn btn-primary btn-sm', rel: 'nofollow' do %>
                <%= _('Preview') %>
              <% end %>
              <%= link_to audit_file_push_path(push), class: 'btn btn-info btn-sm', rel: 'nofollow' do %>
                <%= _('Audit') %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @pushes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <% end %>
</main>

app/views/file_pushes/expired.html.erb
<% title(_('Expired File Pushes')) %>

<main>
  <%= render partial: 'shared/dashboard_header' %>
  <% if @pushes.length.zero? %>
    <p class='text-center mt-3'>
      <%= _('You currently have no expired file pushes.') %>
    </p>
    <p class='text-center'>
      <%= link_to _('Push Something Now'), new_file_push_path, class: 'btn btn-primary' %>
    </p>
  <% else %>
    <div class="text-center my-3">
      <h1 class="display-6"><%= _('Expired File Pushes') %></h1>
    </div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top align-middle" aria-label='<%= _('Active Pushes') %>'>
      <thead>
      <tr>
          <th scope="col"><%= _('ID') %></th>
          <th scope="col"><%= _('Note') %></th>
          <th scope="col"><%= _('Expired On') %></th>
          <th scope="col" class="text-center"><em class='bi-tools'></em></th>
      </tr>
      </thead>
      <tbody class="table-group-divider">
      <% for push in @pushes do %>
        <tr>
          <td><%= push.url_token %></td>
          <td>
            <% if push.note.blank? %>
              <span class='text-muted'><%= _('None') %></span>
            <% else %>
              <div class="text-nowrap overflow-hidden">
                <%= push.note.truncate(30, omission: '...') %>
              </div>
            <% end %>
          </td>
          <td><%= I18n.l push.expired_on, format: :long %></td>
          <td class="text-center">
              <%= link_to audit_file_push_path(push), class: 'btn btn-info btn-sm', rel: 'nofollow' do %>
                <%= _('Audit Log') %>
              <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @pushes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <% end %>
</main>

app/views/file_pushes/new_anonymous.html.erb
<% title(_('Securely Send Files')) %>

<div class='container'>
    <%= render partial: "shared/topnav" %>
    <div class="card text-center w-50 my-5 mx-auto">
        <div class="card-header">
            <em class="bi bi-send-check"></em>
            &nbsp;
            <%= _('Securely Send Files That Delete Automatically') %>
        </div>
        <div class="card-body">
            <% if Settings.disable_signups %>
                <h5 class="card-title"><%= _('Please login to use this feature.') %></h5>
                <p class="card-text"></p>
                <a href="<%= new_user_session_path %>" class="btn btn-primary">Log In</a>
            <% else %>
                <h5 class="card-title"><%= _('Please login or sign up to use this feature.') %></h5>
                <p class="card-text"></p>
                <a href="<%= new_user_session_path %>" class="btn btn-primary">Log In</a>
                <a href="<%= new_user_registration_path %>" class="btn btn-success">Sign Up</a>
            <% end %>
        </div>
    </div>
</div>

app/views/file_pushes/passphrase.html.erb
<% title(_('Enter The Secret Passphrase')) %>

<div class="container-fluid h-100">
  <div class="row d-flex justify-content-center align-items-center h-100 min-vh-100">
        <div class="col col-md-8">
            <div class="card">
                <form action="<%= access_file_push_path %>" method="post" data-no-turbolink=true>
                <div class="input-group">
                    <input type="text" class="form-control" name="passphrase" id="passphrase" autofocus="autofocus"
                      placeholder="<%= _('Enter the secret passphrase provided with this URL') %>" aria-label="<%= _('Enter the secret passphrase') %>" aria-describedby="button-addon2">
                    <button class="btn btn-primary" type="submit" id="button-addon2"><%= _('Go') %></button>
                </div>
                </form>
            </div>
        </div>
  </div>
</div>

app/views/file_pushes/preliminary.html.erb
<div class="container h-100">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <p> <%=link_to _("Click Here to Proceed"), @secret_url %> </p>
    </div>
</div>

app/views/file_pushes/preview.html.erb
<% title(_('Your Push Has Been Created')) %>

<div class="container h-75">
    <div class="d-flex flex-column justify-content-center align-items-center">

      <h2 class='mt-5'><%= _('Your push has been created.') %></h2>

      <p class='mt-5'><%= _('Use this secret link to share it:') %></p>
      <%= render partial: 'shared/secret_url_bar' %>

      <p class='mb-5'>
        <%= _('This push will expire after') %>
        <strong><%=@push.expire_after_days%> <%= n_('day', 'days', @push.expire_after_days) %></strong>
        <%= _('or') %>
        <strong><%=@push.expire_after_views%> <%= n_('view', 'views', @push.expire_after_views) %></strong>
        <%= _('(whichever comes first)') %>

        <% if @push.deletable_by_viewer %>
          <%= _('and') %> <strong><%= _('can be') %></strong> <%= _('deleted by viewers.') %>
        <% else %>
          <%= _('and') %> <strong><%= _('can NOT be') %></strong> <%= _('deleted by viewers.') %>
        <% end %>
      </p>

      <% if @push.retrieval_step == true %>
        <p class='mb-5'><%= _('It also includes a') %> <strong><%= _('1-click preliminary retrieval step') %></strong>.  </p>
      <% end %>

      <p class='mb-5'>
        <%=link_to _('View This Push Now'), @secret_url %> <%= _('(will burn a view) or') %>
        <%=link_to _('Push Another'), new_file_push_path %>
      </p>

      <% if user_signed_in? %>
        <%= link_to audit_file_push_path(@push), class: 'btn btn-secondary btn-sm', rel: 'nofollow' do %>
          <em class='bi-card-list'></em> <%= _('View Audit Log') %>
        <% end %>
      <% end %>

      <p class='mt-5 small'>
        <%= _('Tip: Pushing to an international user?  Change the secret link language using the dropdown menu to the right of the URL.') %>
      </p>
  </div>
</div>

app/views/file_pushes/show.html.erb
<% plain_title(_('Your Secret Link')) %>

<div class="container-fluid h-100 mx-0 py-0 px-0 bg-light">
  <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center bg-light" data-controller="copy passwords" data-copy-lang-copied-value="<%= _('Copied!')%>">
    <% if @push.payload.empty? %>
        <div class='text-center m-3'>
          <p class="display-5"><%= _('The following files have been sent to you.') %></p>
          <p class="text-muted"><%= _('Please download and store in a secure area.') %></p>
          <hr>
        </div>
    <% else %>
        <div class='text-center m-3'>
          <p class=""><strong><%= _('The following message has been sent to you along with the files below.') %></strong></p>
          <% if Settings.files.enable_blur %>
            <p class="text-muted"><%= _('The message is blurred out.  Click below to reveal it.') %></p>
          <% end %>
        </div>

        <% if @payload.chomp.match?(/\n/) || @payload.length > 100 %>
          <div class='payload <%= @blur_css_class %> notranslate px-5 border-top border-bottom border-5 w-100 bg-white d-flex justify-content-center mb-3' id='push_payload' translate='no' data-copy-target="payloadDiv"><pre class='text-break my-5'><%=@payload%></pre></div>
        <% else %>
          <div class='payload <%= @blur_css_class %> notranslate px-5 border-top border-bottom border-5 w-100 bg-white fs-2 mb-3' id='push_payload' translate='no' data-copy-target="payloadDiv"><pre class='w-100 text-break text-wrap my-5 text-center'><%=@payload%></pre></div>
        <% end%>
        <%= render partial: 'shared/copy_button' %>
    <% end %>
    <div class='text-center m-3'>
      <% if @push.files.attached? %>
        <p><strong>Attached Files</strong></p>
          <% @push.files.each do |file| %>
            <div class="list-group">
                <%= link_to rails_blob_url(file), target: '_blank', class: 'list-group-item list-group-item-action' do %>
                  <%= file.filename %>
                  (<%= filesize(file.blob.byte_size) %>)
                  &nbsp;
                  <em class="bi bi-box-arrow-up-right"></em>
                <% end %>
            </div>
          <% end %>
      <% end %>
      <p class="text-muted mt-5">
        <%= _("This secret link and all content will be deleted in") %>
        <strong>
          <%= @push.days_remaining.to_s + ' ' + n_('day', 'days', @push.days_remaining) %>
        </strong>
        <% if @push.views_remaining == 0 %>
            <%= _('or') %> <strong><%= _('0 more views') %></strong>
            <%= _('(this is the last view).') %>
        <% else %>
            <%= _('or') %>
            <strong><%= @push.views_remaining.to_s + ' ' + n_('more view', 'more views', @push.views_remaining) %></strong>
            <%= _('(whichever occurs first).') %>
        <% end %>
      </p>
      <% if @push.deletable_by_viewer %>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
          <em class="bi bi-trash"></em> <%= _('Delete This Secret Link Now') %>
        </button>
      <% end %>
    </div>
  </div>
</div>

<% if @push.deletable_by_viewer %>
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true" data-controller="form">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel"><%= _('Delete?') %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= _('This will expire this secret link and ') %>
          <strong><%= _('delete all related content from the database forever') %></strong>.
          <%= _('Are you sure?') %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= _('Cancel') %></button>
          <%= link_to _('Delete'), @push, data: { turbo_method: :delete, action: 'form#disableWith', 'disable-with': _('Processing...') }, id: @push.url_token, class: 'btn btn-danger', rel: 'nofollow' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/file_pushes/show_expired.html.erb
<% plain_title(_('Your Secret Link Has Expired')) %>

<div class="container h-100">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
      <p class="display-1 text-center p-3 border-bottom">
        <%= _('We apologize but this secret link has expired.') %>
      </p>
      <p class='text-center'><%= _('If needed, please contact the person or organization who gave you this secret URL.') %></p>
    </div>
</div>